### PR TITLE
Executables and such

### PR DESCRIPTION
**Pull request by davidlmorton**

### CODE REVIEW

**Comment by mkiwala** [comment]
Setting the hashbang lines to `#!/usr/bin/perl` is a correct and simple fix.  I'm pretty sure it's common practice to fixup the hashbang lines when building the distribution tarball.  I would support using whatever the common solution is for this problem, unless it looks too icky.

**Comment by mkiwala** [comment]
There is support in ExtUtils::MakeMaker by means of the `fixin()` function in `ExtUtils::MM_Unix` to replace something like `#!perl` with something else.   I'm not sure it's going to simplify anything for us, so nevermind for now.

**Comment by iferguson90** [comment]
What's the reasoning behind changing the hashbangs?

For what it's worth I see some projects on GitHub just using `#!perl`.

My gut feeling is to remove `perl` from the `commandLine` and either use `#!perl` or go back to `#!/usr/bin/env perl`. Then a Debian package can replace the hashbangs to use the system Perl.

**Comment by iferguson90** [comment]
Found this in the [debhelper documentation](https://pkg-perl.alioth.debian.org/debhelper.html#fixing_interpreter_shebang_lines):

> ## Fixing Interpreter Shebang Lines
> 
> Sometimes examples are Perl scripts that do not use the absolute path of the Perl interpreter in the shebang line. In these cases, they should be rewritten to _/usr/bin/perl_:
>
> ```
> override_dh_installexamples:
> 	dh_installexamples
> 	sed -i '1s|^#!perl|#!/usr/bin/perl|' $(TMP)/usr/share/doc/$(PACKAGE)/examples/*
> ```
> Another elegant method for achieving substitution of the shebang from /usr/local/bin/perl to /usr/bin/perl would be:
>
> ```
> override_dh_installexamples:
> 	dh_installexamples
> 	find $(TMP)/usr/share/doc/$(PACKAGE)/examples -type f -print0 | \
> 		xargs -r0 sed -i -e '1s|^#!/usr/local/bin/perl|#!/usr/bin/perl|'
> ```

**Comment by mkiwala** [comment]
We've updated the `lucid` branch to handle `hashbang` lines, so that `#!/usr/bin/env perl` is translated to `#!/usr/bin/perl` under the debhelper `dh_install` rule.

**Comment by iferguson90** [comment]
:+1:

**Pull request merged**
